[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -I ../common/include

lib_deps =
    adafruit/Adafruit TCS34725 @ ^1.4.4
    waspinator/AccelStepper @ ^1.64
    bblanchon/ArduinoJson @ ^6.21.3
    Wire
